window:
  dimensions:
    columns: 80
    lines: 24

  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
      x: 0
      y: 0

  # Spread additional padding evenly around the terminal content.
  #dynamic_padding: false

  # Window decorations
  #
  # Values for `decorations`:
  #     - full: Borders and title bar
  #     - none: Neither borders nor title bar
  #
  # Values for `decorations` (macOS only):
  #     - transparent: Title bar, transparent background and title bar buttons
  #     - buttonless: Ttle bar, transparent background, but no title bar buttons
  decorations: none

  # Startup Mode (changes require restart)
  #
  # Values for `startup_mode`:
  #   - Windowed
  #   - Maximized
  #   - Fullscreen
  #
  # Values for `startup_mode` (macOS only):
  #   - SimpleFullscreen
  startup_mode: Maximized

  # Window title
  #title: Alacritty

  # Window class (Linux/BSD only):
  #class:
    # Application instance name
    #instance: Alacritty
    # General application class
    #general: Alacritty

  # GTK theme variant (Linux/BSD only)
  #
  # Override the variant of the GTK theme. Commonly supported values are `dark` and `light`.
  # Set this to `None` to use the default theme variant.
  gtk_theme_variant: dark

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 10000

  # Number of lines the viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  #multiplier: 3

#Font configuration
font:
  normal:
    family: Fira Code
    style: Medium
  bold:
    family: Fira Code
    style: Bold
  # italic:
  #   family: Fira Code
  #   style: Italic

  # Point size
  size: 13

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  #offset:
  #  x: 0
  #  y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the right,
  # increasing `y` moves the glyph upwards.
  #glyph_offset:
  #  x: 0
  #  y: 0

draw_bold_text_with_bright_colors: true

# # Dracula Color Scheme:
# colors:
#   primary:
#     background: '#282a36'
#     foreground: '#f8f8f2'
#   cursor:
#     text:       '#44475a'
#     cursor:     '#f8f8f2'
#   normal:
#     black:      '#282c34'
#     red:        '#ff5555'
#     green:      '#50fa7b'
#     yellow:     '#f1fa8c'
#     blue:       '#bd93f9'
#     magenta:    '#ff79c6'
#     cyan:       '#8be9fd'
#     white:      '#bfbfbf'
#   bright:
#     black:      '#4d4d4d'
#     red:        '#ff6e67'
#     green:      '#5af78e'
#     yellow:     '#f4f99d'
#     blue:       '#caa9fa'
#     magenta:    '#ff92d0'
#     cyan:       '#9aedfe'
#     white:      '#e6e6e6'

# # Nord Theme
# colors:
#   primary:
#     background: '#2E3440'
#     foreground: '#D8DEE9'
#   cursor:
#     text: '#2E3440'
#     cursor: '#D8DEE9'
#   normal:
#     black: '#3B4252'
#     red: '#BF616A'
#     green: '#A3BE8C'
#     yellow: '#EBCB8B'
#     blue: '#81A1C1'
#     magenta: '#B48EAD'
#     cyan: '#88C0D0'
#     white: '#E5E9F0'
#   bright:
#     black: '#4C566A'
#     red: '#BF616A'
#     green: '#A3BE8C'
#     yellow: '#EBCB8B'
#     blue: '#81A1C1'
#     magenta: '#B48EAD'
#     cyan: '#8FBCBB'
#     white: '#ECEFF4'

# Gruvbox
colors:
  primary:
    foreground: '#ebdbb2'
    background: '#282828'
  cursor:
    cursor:     '#c5c8c6'
  normal:
    black:      '#333333'
    red:        '#cc241d'
    green:      '#98971a'
    yellow:     '#d79921'
    blue:       '#458588'
    magenta:    '#b16286'
    cyan:       '#689d6a'
    white:      '#a89984'
  bright:
    black:      '#928374'
    red:        '#fb4934'
    green:      '#b8bb26'
    yellow:     '#fabd2f'
    blue:       '#83a598'
    magenta:    '#d3869b'
    cyan:       '#8ec07c'
    white:      '#ebdbb2'

# # Solarized
# colors:
#   primary:
#     background: '#002b36'
#     foreground: '#93a1a1'
#   normal:
#     black:   '#002b36'
#     red:     '#dc322f'
#     green:   '#859900'
#     yellow:  '#b58900'
#     blue:    '#268bd2'
#     magenta: '#6c71c4'
#     cyan:    '#2aa198'
#     white:   '#93a1a1'
#   bright:
#     black:   '#657b83'
#     red:     '#dc322f'
#     green:   '#859900'
#     yellow:  '#b58900'
#     blue:    '#268bd2'
#     magenta: '#6c71c4'
#     cyan:    '#2aa198'
#     white:   '#fdf6e3'

# Google Dark Scheme:
# colors:
#   primary:
#     background: '#1d1f21'
#     foreground: '#c5c8c6'
#   cursor:
#     text:       '#44475a'
#     cursor:     '#f8f8f2'
#   normal:
#     black:      '#1d1f21'
#     red:        '#cc342b'
#     green:      '#198844'
#     yellow:     '#fba922'
#     blue:       '#3971ed'
#     magenta:    '#a36ac7'
#     cyan:       '#00ccff'
#     white:      '#c5c8c6'
#   bright:
#     black:      '#333333'
#     red:        '#cc342b'
#     green:      '#198844'
#     yellow:     '#fba922'
#     blue:       '#3971ed'
#     magenta:    '#a36ac7'
#     cyan:       '#00ccff'
#     white:      '#ffffff'

# Blossom Scheme:
# colors:
#   primary:
#     background: '#22272C'
#     foreground: '#F2F2F4'
#   cursor:
#     text:       '#44475a'
#     cursor:     '#f8f8f2'
#   normal:
#     black:      '#445158'
#     red:        '#FF6565'
#     green:      '#2CC46E'
#     yellow:     '#ECC46F'
#     blue:       '#6F97EC'
#     magenta:    '#FA5477'
#     cyan:       '#64B9F2'
#     white:      '#D2D2D4'
#   bright:
#     black:      '#5E6B72'
#     red:        '#FF7272'
#     green:      '#46DE88'
#     yellow:     '#FFDE89'
#     blue:       '#89B1FF'
#     magenta:    '#FF6E91'
#     cyan:       '#71C6FF'
#     white:      '#F1F1F3'

background_opacity: 1

selection:
  #semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true

# Allow terminal applications to change Alacritty's window title.
window.dynamic_title: true

cursor:
  # Values for `style`:
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style: Underline
  unfocused_hollow: false

# Live config reload (changes require restart)
live_config_reload: true

shell:
  program: /bin/zsh

# To trigger mouse bindings when an application running within Alacritty captures the mouse, the
# `Shift` modifier is automatically added as a requirement.
#
# Each mouse binding will specify a:
#   - Middle
#   - Left
#   - Right
#   - Numeric identifier such as `5`
mouse_bindings:
  - { mouse: Middle, action: PasteSelection }
  - { mouse: Right,  action: PasteSelection }

# Key bindings
#
# Each key binding will specify a:
#
# - `key`: Identifier of the key pressed
#
#    - A-Z
#    - F1-F24
#    - Key0-Key9
#
#    A full list with available key codes can be found here:
#    https://docs.rs/glutin/*/glutin/event/enum.VirtualKeyCode.html#variants
#
#    Instead of using the name of the keys, the `key` field also supports using
#    the scancode of the desired key. Scancodes have to be specified as a
#    decimal number. This command will allow you to display the hex scancodes
#    for certain keys:
#
#       `showkey --scancodes`.
#
# Then exactly one of:
#
# - `chars`: Send a byte sequence to the running application
#
#    The `chars` field writes the specified string to the terminal. This makes
#    it possible to pass escape sequences. To find escape codes for bindings
#    like `PageUp` (`"\x1b[5~"`), you can run the comman `showkey -a` outside
#    of tmux. Note that applications use terminfo to map escape sequences back
#    to keys. It is therefore required to update the terminfo when changing an
#    escape sequence.
#
# - `action`: Execute a predefined action
#
#   - Copy
#   - Paste
#   - PasteSelection
#   - IncreaseFontSize
#   - DecreaseFontSize
#   - ResetFontSize
#   - ScrollPageUp
#   - ScrollPageDown
#   - ScrollLineUp
#   - ScrollLineDown
#   - ScrollToTop
#   - ScrollToBottom
#   - ClearHistory
#   - Hide
#   - Minimize
#   - Quit
#   - ToggleFullscreen
#   - SpawnNewInstance
#   - ClearLogNotice
#   - ReceiveChar
#   - None
#
# - `command`: Fork and execute a specified command plus arguments
#
#    The `command` field must be a map containing a `program` string and an
#    `args` array of command line parameter strings. For example:
#       `{ program: "alacritty", args: ["-e", "vttest"] }`
#
# And optionally:
#
# - `mods`: Key modifiers to filter binding actions
#
#    - Command
#    - Control
#    - Option
#    - Super
#    - Shift
#    - Alt
#
#    Multiple `mods` can be combined using `|` like this:
#       `mods: Control|Shift`.
#    Whitespace and capitalization are relevant and must match the example.
#
# - `mode`: Indicate a binding for only specific terminal reported modes
#
#    This is mainly used to send applications the correct escape sequences
#    when in different modes.
#
#    - AppCursor
#    - AppKeypad
#    - Alt
#
#    A `~` operator can be used before a mode to apply the binding whenever
#    the mode is *not* active, e.g. `~Alt`.
#
# Bindings are always filled by default, but will be replaced when a new
# binding with the same triggers is defined. To unset a default binding, it can
# be mapped to the `ReceiveChar` action. Alternatively, you can use `None` for
# a no-op if you do not wish to receive input characters for that binding.
key_bindings:
  - { key: V,        mods: Control|Shift, action: Paste            }
  - { key: C,        mods: Control|Shift, action: Copy             }
  - { key: V,        mods: Alt,           action: Paste            }
  - { key: C,        mods: Alt,           action: Copy             }
  - { key: Insert,   mods: Shift,         action: PasteSelection   }
  - { key: Key0,     mods: Control|Shift, action: ResetFontSize    }
  - { key: Equals,   mods: Control|Shift, action: IncreaseFontSize }
  - { key: Add,      mods: Control|Shift, action: IncreaseFontSize }
  - { key: Subtract, mods: Control|Shift, action: DecreaseFontSize }
  - { key: Minus,    mods: Control|Shift, action: DecreaseFontSize }
  - { key: Paste,                    action: Paste                            }
  - { key: Copy,                     action: Copy                             }
