#!/bin/sh

picom --experimental-backends -o 0 --refresh-rate 75 --backend glx --glx-no-stencil &
# Other Picom toggles: -b --vsync --no-fading-openclose
# nvidia-settings --config="$XDG_CONFIG_HOME/nvidia-settings-rc" &
# weather &
dwmbar &
clipmenud &
sxhkd &
xset r rate 200 50 &
nitrogen --restore &
