#!/bin/sh

picom -b --experimental-backends --backend glx --glx-no-stencil &
# Other Picom toggles: -b --vsync --no-fading-openclose --refresh-rate 75
# nvidia-settings --config="$XDG_CONFIG_HOME/nvidia-settings-rc" &
# dwmbar &
clipmenud &
sxhkd &
xset r rate 150 60 &
nitrogen --restore &
